Devex 943: Try running npm install twice to see if cache works in the same job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -748,26 +748,27 @@ jobs:
     steps:
       - git-shallow-clone/checkout
       - npm-install
-      - run:
-          name: Create Cypress Artifacts Directory
-          command: mkdir /tmp/cypress
-      - run:
-          name: Setup Env
-          command: |
-            cat "./env-for-circle/${CIRCLE_BRANCH}${CONFIG_SUFFIX}.sh" >> $BASH_ENV
-            source $BASH_ENV
-            echo "export DEPLOYING_COLOR=$(./scripts/get-deploying-color.sh $ENV)" >> $BASH_ENV
-      - run:
-          name: 'Disable Maintenance Mode'
-          command: npm run maintenance:disengage $ENV
-      - run:
-          name: 'Cypress Smoke Tests'
-          command: npm run cypress:smoketests
-      - run:
-          name: 'Pa11y Smoke Tests'
-          command: npm run test:pa11y:smoketests
-      - store_artifacts:
-          path: /root/project/cypress-smoketests/videos/
+      - npm-install
+      # - run:
+      #     name: Create Cypress Artifacts Directory
+      #     command: mkdir /tmp/cypress
+      # - run:
+      #     name: Setup Env
+      #     command: |
+      #       cat "./env-for-circle/${CIRCLE_BRANCH}${CONFIG_SUFFIX}.sh" >> $BASH_ENV
+      #       source $BASH_ENV
+      #       echo "export DEPLOYING_COLOR=$(./scripts/get-deploying-color.sh $ENV)" >> $BASH_ENV
+      # - run:
+      #     name: 'Disable Maintenance Mode'
+      #     command: npm run maintenance:disengage $ENV
+      # - run:
+      #     name: 'Cypress Smoke Tests'
+      #     command: npm run cypress:smoketests
+      # - run:
+      #     name: 'Pa11y Smoke Tests'
+      #     command: npm run test:pa11y:smoketests
+      # - store_artifacts:
+      #     path: /root/project/cypress-smoketests/videos/
 
   smoketests-readonly:
     docker:
@@ -779,36 +780,36 @@ jobs:
     steps:
       - git-shallow-clone/checkout
       - npm-install
-      - run:
-          name: Create Cypress Artifacts Directory
-          command: mkdir /tmp/cypress
-      - run:
-          name: Setup Env
-          command: |
-            cat "./env-for-circle/${CIRCLE_BRANCH}${CONFIG_SUFFIX}.sh" >> $BASH_ENV
-            source $BASH_ENV
-            echo "export DEPLOYING_COLOR=$(./scripts/get-deploying-color.sh $ENV)" >> $BASH_ENV
-      - run:
-          name: Create and Enable Test User
-          command: node ./scripts/create-and-enable-smoketest-user.js
-      - run:
-          name: 'Cypress Readonly Smoke Tests'
-          command: |
-            set +e
-            npm run cypress:readonly
-            echo "export READONLY_SMOKETESTS_RESULT=$?" >> $BASH_ENV
-            set -e
-      - run:
-          name: Disable Test User
-          command: node ./scripts/disable-smoketest-user.js
-      - run:
-          name: Kill Build if Smoketests Failed
-          command: ./scripts/kill-circle-build.sh
-      - run:
-          name: 'Cypress Public Readonly Smoke Tests'
-          command: npm run cypress:readonly:public
-      - store_artifacts:
-          path: /root/project/cypress-readonly/videos/
+      # - run:
+      #     name: Create Cypress Artifacts Directory
+      #     command: mkdir /tmp/cypress
+      # - run:
+      #     name: Setup Env
+      #     command: |
+      #       cat "./env-for-circle/${CIRCLE_BRANCH}${CONFIG_SUFFIX}.sh" >> $BASH_ENV
+      #       source $BASH_ENV
+      #       echo "export DEPLOYING_COLOR=$(./scripts/get-deploying-color.sh $ENV)" >> $BASH_ENV
+      # - run:
+      #     name: Create and Enable Test User
+      #     command: node ./scripts/create-and-enable-smoketest-user.js
+      # - run:
+      #     name: 'Cypress Readonly Smoke Tests'
+      #     command: |
+      #       set +e
+      #       npm run cypress:readonly
+      #       echo "export READONLY_SMOKETESTS_RESULT=$?" >> $BASH_ENV
+      #       set -e
+      # - run:
+      #     name: Disable Test User
+      #     command: node ./scripts/disable-smoketest-user.js
+      # - run:
+      #     name: Kill Build if Smoketests Failed
+      #     command: ./scripts/kill-circle-build.sh
+      # - run:
+      #     name: 'Cypress Public Readonly Smoke Tests'
+      #     command: npm run cypress:readonly:public
+      # - store_artifacts:
+      #     path: /root/project/cypress-readonly/videos/
 
   switch-colors:
     docker:
