devex-1136: added the ability to kick off the glue job workflow via an API call and the ability to run glue jobs to any lower env more easily.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,6 +3,23 @@ orbs:
   git-shallow-clone: guitarrapc/git-shallow-clone@2.5.0
 efcms-docker-image: &efcms-docker-image $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/ef-cms-us-east-1:3.0.5
 
+parameters:
+  run_build_and_deploy:
+    default: true
+    type: boolean
+
+  run_build_and_deploy_with_context:
+    default: true
+    type: boolean
+
+  run_glue_to_lower_env:
+    default: false
+    type: boolean
+
+  lower_env:
+    default: test
+    type: string
+
 commands:
   npm-and-cypress-install:
     steps:
@@ -40,6 +57,7 @@ commands:
           key: v27-cypress-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
           paths:
             - ~/.cache/Cypress
+
   npm-install:
     steps:
       - restore_cache:
@@ -62,7 +80,7 @@ commands:
             - node_modules
 
 jobs:
-  prepare-for-glue-job:
+  initiate-glue-job:
     docker:
       - image: *efcms-docker-image
         aws_auth:
@@ -74,25 +92,53 @@ jobs:
       - npm-install
       - run:
           name: Setup Env
-          command: |
-            ./scripts/env/env-for-circle.sh
+          command: ./scripts/env/env-for-circle.sh
       - run:
           name: Setup the deploy table for a glue job
-          command: |
-            ./scripts/setup-deploy-table-for-glue-job.sh
+          command: ./scripts/setup-deploy-table-for-glue-job.sh
       - run:
           name: Delete all existing dynamodb tables and elasticsearch clusters
-          command: |
-            ./scripts/delete-all-persistence.sh
+          command: ./scripts/delete-all-persistence.sh
       - run:
           name: Kick off a deployment
+          command: |
+            VCS=<< pipeline.project.type >>
+            PIPELINE_ID=$(curl --request POST \
+              --url "https://circleci.com/api/v2/project/${VCS}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline" \
+              --header "Circle-Token: ${CIRCLE_MACHINE_USER_TOKEN}" \
+              --header "content-type: application/json" \
+              --data "{\"branch\":\"${CIRCLE_BRANCH}\"}" | jq -r '.id')
+            echo "export PIPELINE_ID=${PIPELINE_ID}" >> $BASH_ENV
+      - run:
+          name: Wait for deployment to complete
+          command: |
+            PIPELINE_STATUS=$(curl --request GET \
+              --url "https://circleci.com/api/v2/pipeline/${PIPELINE_ID}/workflow?circle-token=$CIRCLE_TOKEN" \
+              --header "Circle-Token: ${CIRCLE_MACHINE_USER_TOKEN}" \
+              --header "content-type: application/json" | jq -r '.items[].status')
+            while [[ "$PIPELINE_STATUS" == "running" ]]; do
+              echo "Pipeline ${PIPELINE_ID} is running"
+              sleep 60
+              PIPELINE_STATUS=$(curl --request GET \
+                --url "https://circleci.com/api/v2/pipeline/${PIPELINE_ID}/workflow?circle-token=$CIRCLE_TOKEN" \
+                --header "Circle-Token: ${CIRCLE_MACHINE_USER_TOKEN}" \
+                --header "content-type: application/json" | jq -r '.items[].status')
+            done
+            if [[ "$PIPELINE_STATUS" == "success" ]]; then
+              echo "Pipeline ${PIPELINE_ID} completed successfully"
+            else
+              echo "Pipeline ${PIPELINE_ID} did not complete: ${PIPELINE_STATUS}"
+              exit 1
+            fi
+      - run:
+          name: Kick off the glue-to-lower-env workflow
           command: |
             VCS=<< pipeline.project.type >>
             curl --request POST \
               --url "https://circleci.com/api/v2/project/${VCS}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline" \
               --header "Circle-Token: ${CIRCLE_MACHINE_USER_TOKEN}" \
               --header "content-type: application/json" \
-              --data "{\"branch\":\"${CIRCLE_BRANCH}\"}"
+              --data "{\"branch\":\"prod\", \"parameters\":{\"run_build_and_deploy_with_context\":false, \"run_glue_to_lower_env\":true, \"lower_env\":\"${CIRCLE_BRANCH}\"}}"
 
   start-glue-job:
     docker:
@@ -108,6 +154,12 @@ jobs:
           name: Setup Env
           command: |
             ./scripts/env/env-for-circle.sh
+            LOWER_ENV=<< pipeline.parameters.lower_env >>
+            if [[ -z "$LOWER_ENV" ]]; then
+              echo "Error: no lower environment was provided"
+              exit 1
+            fi
+            echo "export LOWER_ENV=${LOWER_ENV}" >> $BASH_ENV
       - run:
           name: Deploy Check Glue Job Run State Cron Lambda
           command: |
@@ -115,7 +167,7 @@ jobs:
       - run:
           name: Start Glue Job
           command: |
-            npx ts-node --transpile-only shared/admin-tools/glue/start-glue-job.ts efcms-test-alpha
+            npx ts-node --transpile-only shared/admin-tools/glue/start-glue-job.ts "efcms-${LOWER_ENV}-alpha"
       - run:
           name: Enable Check Glue Job Run State Cron
           command: |
@@ -608,6 +660,7 @@ workflows:
   version: 2
 
   build-and-deploy:
+    when: << pipeline.parameters.run_build_and_deploy >>
     jobs:
       - deploy:
           <<: *build-and-deploy-defaults
@@ -655,6 +708,7 @@ workflows:
             - switch-colors
 
   build-and-deploy-with-context:
+    when: << pipeline.parameters.run_build_and_deploy_with_context >>
     jobs:
       - deploy:
           <<: *build-and-deploy-with-context-defaults
@@ -719,19 +773,18 @@ workflows:
             - backup-source-dynamo-table
             - delete-api-mappings
 
-  prepare-test-env-for-glue-job:
+  glue-to-test:
     when:
-      equal: [ prepare-test-env-for-glue-job-schedule, << pipeline.schedule.name >> ]
+      equal: [ glue-to-test-schedule, << pipeline.schedule.name >> ]
     jobs:
-      - prepare-for-glue-job:
+      - initiate-glue-job:
           filters:
             branches:
               only:
                 - test
 
-  glue-to-test:
-    when:
-      equal: [ perform-glue-job-to-test-schedule, << pipeline.schedule.name >> ]
+  glue-to-lower-env:
+    when: << pipeline.parameters.run_glue_to_lower_env >>
     jobs:
       - start-glue-job:
           <<: *build-and-deploy-with-context-defaults
